<?php
return array(
  // Common
  'ILLEGAL_LOGIN' => array(1001, 'illegal login'),
  'QUERY_FAILED' => array(1002, 'get info failed'),
  'PAGE_IS_INVALID' => array(1003, 'page is invalid'),
  'LISTROWS_IS_INVALID' => array(1004, 'listrows is invalid'),
  'BLACK_IP' => array(1005, 'ip is forbidden'),

  // User
  'USER_BE_KICKED_OFFLINE' => array(1100, 'user be kicked offline'),
  'USER_IS_NOT_EXIST' => array(1101, 'user is not exist'),
  'USER_STATUS_EXPIRED' => array(1102, 'user status expired'),
  'TYPE_IS_INVALID' => array(1103, 'type is invalid'),
  'MOBILE_IS_INVALID' => array(1104, 'mobile is invalid'),
  'USER_IS_ALREADY_EXIST' => array(1105, 'user is already exist'),
  'PLEASE_WAIT_A_MOMENT' => array(1106, 'please wait a moment'),
  'ILLEGAL_IP_ADDRESS' => array(1107, 'illegal ip address'),
  'VERIFY_CODE_LOG_FAILED' => array(1108, 'verify code log failed'),
  'ATTAIN_DAILY_REQUEST_LIMIT' => array(1109, 'attain daily request limit'),
  'VERIFY_CODE_IS_INVALID' => array(1110, 'verify code is invalid'),
  'PASSWORD_IS_INVALID' => array(1111, 'password is invalid'),
  'MOBILE_IS_WRONG' => array(1112, 'mobile is wrong'),
  'VERIFY_CODE_IS_WRONG' => array(1113, 'verify code is wrong'),
  'REGISTER_FAILED' => array(1114, 'register failed'),
  'TOKEN_UPDATE_FAILED' => array(1115, 'token update failed'),
  'PASSWORD_IS_WRONG' => array(1116, 'password is wrong'),
  'PASSWORD_EDIT_FAILED' => array(1117, 'password edit failed'),
  'GET_VERIFY_CODE_FAILED' => array(1118, 'get verify code failed'),
  'USER_ID_IS_INVALID' => array(1119, 'user id is invalid'),
  'USER_DISABLE_FAILED' => array(1120, 'user disable failed'),
  'USER_ENABLE_FAILED' => array(1121, 'user enable failed'),
  'ORGANIZATION_IS_INVALID' => array(1122, 'organization is invalid'),
  'INDUSTRY_IS_INVALID' => array(1123, 'industry is invalid'),
  'PROVINCE_IS_INVALID' => array(1124, 'province is invalid'),
  'CITY_IS_INVALID' => array(1125, 'city is invalid'),
  'USER_LIST_IS_EMPTY' => array(1126, 'user list is empty'),
  'USER_MOBILE_HAS_EXISTED' => array(1127, 'user mobile has existed'),
  'USER_MODIFY_FAILED' => array(1128, 'user modify failed'),
  'USER_IS_ALREADY_APPLIED' => array(1129, 'user is already applied'),
  'USER_AVATOR_IS_INVALID' => array(1130, 'user avator is invalid'),
  'INVITE_CODE_IS_INVALID' => array(1131, 'invite code is invalid'),
  'NO_WITHDRAWABLE_AMOUNT' => array(1132, 'no withdrawable amount'),
  'WITHDRAW_FAILED' => array(1133, 'withdraw failed'),
  'ACCOUNT_FLOW_TYPE_IS_INVALID' => array(1134, 'account flow type is invalid'),
  'NO_ENOUGH_AMOUNT_TO_WITHDRAW' => array(1135, 'no enough amount dto withraw'),
  'USERNAME_IS_WRONG' => array(1136, 'username is wrong'),
  'TRUENAME_IS_INVALID' => array(1137, 'truename is invalid'),
  'WITHDRAW_AMOUNT_IS_TO_LESS' => array(1138, 'amount is too less'),
  'WITHDRAW_AMOUNT_IS_TO_LARGE' => array(1139, 'amount is too large'),
  'WITHDRAW_AMOUNT_IS_INVALID' => array(1140, 'amount is invalid'),
  'USER_LOGGED_IN_OTHER_PLACES' => array(1141, 'user has logged in other places'),
  'LOGIN_FORCE_IS_INVALID' => array(1142, 'login force is invalid'),
  'USER_ACCOUNT_TYPE_IS_INVALID' => array(1143, 'user account type is invalid'),
  'HAS_NOT_BIND_ACCOUNT' => array(1144, 'there is no binding account'),
  'ACCOUNT_IS_INVALID' => array(1145, 'account is invalid'),
  'ACCOUNT_NAME_IS_INVALID' => array(1146, 'account name is invalid'),
  'ID_CARD_IS_INVALID' => array(1147, 'ID card is invalid'),
  'BANK_ACCOUNT_IS_INVALID' => array(1148, 'bank account is invalid'),
  'HAS_ALREADY_BOUND_THE_ACCOUNT' => array(1149, 'has already bound the account'),
  'ACCOUNT_BIND_FALID' => array(1150, 'account bind fail'),
  'ALREADY_WITHDRAW_TODAY' => array(1151, 'already withdraw today'),
  'TOKEN_USER_ID_MISMATCH' => array(1152, 'token user id mismatch'),
  'TOKEN_HAS_EXPIRED' => array(1153, 'token has expired'),

  // Activity
  'TITLE_IS_INVALID' => array(1201, 'title is invalid'),  'START_TIME_IS_INVALID' => array(1202, 'start time is invalid'),
  'END_TIME_IS_INVALID' => array(1203, 'end time is invalid'),
  'RULES_IS_INVALID' => array(1204, 'rules is invalid'),
  'PRIZES_IS_INVALID' => array(1205, 'prizes is invalid'),
  'RECEIVE_INFO_IS_INVALID' => array(1206, 'receive info is invalid'),
  'EXCHANGE_OPERATION_FAILED' => array(1207, 'exchange operation failed'),
  'NOBODY_JOIN_ACTIVITY' => array(1208, 'nobody join activity'),
  'HOST_INFO_IS_INVALID' => array(1209, 'host info is invalid'),
  'HOST_IMG_IS_INVALID' => array(1210, 'host img is invalid'),
  'ACTIVITY_CREATE_FAILED' => array(1212, 'activity create failed'),
  'ACTIVITY_ID_IS_INVALID' => array(1213, 'activity id is invalid'),
  'UPDATE_INFO_IS_EMPTY' => array(1214, 'update info is empty'),
  'ACTIVITY_UPDATE_FAILED' => array(1215, 'activity_update_failed'),
  'ACTIVITY_LIST_IS_EMPTY' => array(1216, 'activity list is empty'),
  'ACTIVITY_IS_NOT_EXIST' => array(1217, 'activity is not exist'),
  'NAME_IS_INVALID' => array(1218, 'name is invalid'),
  'USER_HAS_ALREADY_JOINED_ACTIVITY' => array(1219, 'user has already joined activity'),
  'JOIN_ACTIVITY_FAILED' => array(1220, 'join activity failed'),
  'JOINER_ID_IS_INVALID' => array(1221, 'joiner id is invalid'),
  'VOTE_FAILED' => array(1222, 'vote failed'),
  'YOU_HAVE_ALREADY_VOTED' => array(1223, 'you have already voted'),
  'SHARE_TITLE_IS_INVALID' => array(1224, 'share title is invalid'),
  'SHARE_CONTENT_IS_INVALID' => array(1225, 'share content is invalid'),
  'SHARE_IMAGE_IS_INVALID' => array(1226, 'share image is invalid'),
  'SHARE_INFO_UPDATE_FAILED' => array(1227, 'share info update failed'),
  'ACTIVITY_HAS_NOT_STARTED' => array(1228, 'activity has not started'),
  'ACTIVITY_HAS_BEEN_COMPLETED' => array(1229, 'activity has been completed'),
  'ACTIVITY_DURATION_IS_WRONG' => array(1230, 'activity duration is wrong'),
  'ACTIVITY_DELETE_FAILED' => array(1231, 'activity delete failed'),
  'ALREADY_EXCHANGED_PRIZES' => array(1232, 'already exchanged prizes'),
  'PRIZES_HAVE_BEEN_RECEIVED_OVER' => array(1233, 'prizes have been received over'),
  'TARGET_HAS_BEEN_COMPLETED' => array(1234, 'target has been completed'),
  'NOBODY_COMPLETE' => array(1235, 'no body complete'),
  'ACTIVITY_IS_NOT_MATCH' => array(1236, 'activity is not match'),
  'KEYWORD_IS_INVALID' => array(1237, 'keyword is invalid'),
  'SEARCH_RESULT_IS_EMPTY' => array(1238, 'search result is empty'),
  'DO_NOT_TOUCH_DISCOUNT_LEVEL' => array(1239, 'not yet reached the discount level'),
  'ACTIVITY_PRIZES_HAS_FULL' => array(1240, 'prizes are full'),
  'HAS_WON_THE_PRIZE' => array(1241, 'you have won the prize'),
  'HAS_WON_OTHER_PRIZE' => array(1242, 'you have won other prize'),
  'PRIZES_FORMAT_IS_INVALID' => array(1243, 'prize format is invalid'),
  'NOBODY_WIN_THE_ACTIVITY_PRIZE' => array(1244, 'no body win the activity prize'),
  'ACTIVITY_WIN_RECORD_IS_INVALID' => array(1245, 'activity win record is invalid'),
  'REMOVE_WIN_RECORD_FAILED' => array(1246, 'remove joiner win record failed'),
  'ACTIVITY_PRIZE_LEVEL_IS_INVALID' => array(1247, 'activity prize level is invalid'),
  'SEARCH_TYPE_IS_INVALID' => array(1248, 'search type is invalid'),
  'NEXT_VOTE_DATE_IS_INVALID' => array(1249, 'next vote date is invalid'),
  'ACTIVITY_ENABLE_FAILED' => array(1250, 'activity enable failed'),
  'ACTIVITY_REMOVE_JOINER_FAILED' => array(1251, 'remove joiner failed'),
  'ACTIVITY_JOINER_HAS_BEEN_REMOVED' => array(1252, 'activity joiner has been remove'),
  'ACTIVITY_JOINER_MODIFY_FAILED' => array(1253, 'activity joiner modify faild'),
  'OTHERS_IS_INVALID' => array(1254, 'activity joiner modify faild'),
  'ACTIVITY_SET_TO_CASE_FAILED' => array(1255, 'activity set to case failed'),
  'ACTIVITY_SAVE_PRIZES_FAILED' => array(1256, 'activity save prizes failed'),
  'ACTIVITY_PRIZES_IS_NORMAL' => array(1257, 'activity prizes is normal'),
  'HAS_REACH_THE_PRIZE_LIMIT' => array(1258, 'has reached the prize limit'),
  'JOINER_AVATOR_IS_INVALID' => array(1259, 'joiner avator is invalid'),
  'PROCESSING_ACTIVITIES_HAS_FULL' => array(1260, 'processing activities has be full'),
  'ACTIVITY_PERIOD_OUTOF_RANGE' => array(1261, 'activity period out of the range'),
  'ACTIVITY_STARTTIME_UNABLE_TO_CHANGE' => array(1262, 'activity start time unable to change'),
  'CONTENT_IS_INVALID' => array(1263, 'activity content is invalid'),
  'ACTIVITY_NEEDS_TO_BE_PAID' => array(1264, 'activity needs to be paid'),
  'JOINERS_HAD_BEEN_FULL' => array(1265, 'joiners has been full'),
  'SETTLED_FAILED' => array(1266, 'settle failed'),
  'NO_BILLABLE_AMOUNT' => array(1267, 'no billable amount'),
  'GET_BLACK_JOINERS_FAILD' => array(1268, 'get black joiners failed'),
  'ORDER_IS_NOT_EXISTED' => array(1269, 'order is not existed'),
  'EXCEPTION_ORDER_ID_IS_INVALID' => array(1270, 'exception order id is invalid'),
  'ACTIVITY_NOT_OPEN_PAYMENT' => array(1271, 'activity not open payment'),
  'SHARE_HOST_IS_INVALID' => array(1272, 'share hostname is invalid'),
  'VOTE_CODE_IS_INVALID' => array(1273, 'vote code is invalid'),
  'HELPER_NAME_IS_INVALID' => array(1274, 'helper name is invalid'),
  'HAS_ALREADY_VOTED_TODAY' => array(1275, 'has been already voted today'),
  "HAS_ALREADY_REACH_VOTE_LIMIT" => array(1276, 'has already reach vote limit'),
  "JOINER_REMARK_IS_REQUIRE" => array(1277, 'joiner remark is required'),
  "ACTIVITY_QRCODE_GENERATE_FAILED" => array(1278, 'activity qrcode generate failed'),
  "ACTIVITY_QRCODE_PARAMS_INVALID" => array(1279, 'activity qrcode params invalid'),
  "JOINER_UUID_INVALID" => array(1280, 'joiner uuid is invalid'),
  "JOINER_UUID_ALREADY_EXISTED" => array(1281, 'joiner uuid has existed'),
  "PHOTO_SIZE_IS_INVALID" => array(1282, 'photo size is invalid'),
  "PHOTO_SIZE_MODIFY_FAILED" => array(1283, 'photo size modify failed'),
  "VERIFY_TYPE_IS_REQUIRED" => array(1284, 'verify type is required'),
  "VERIFY_CODE_IS_REQUIRE" => array(1285, 'verify code is invalid'),
  "USER_NICKNAME_IS_INVALID" => array(1286, 'user nickname is invalid'),
  "OTHERS_IS_INVALID" => array(1287, 'others is invalid'),

  // Complaint
  'COMPLAINT_CONTENT_IS_INVALID' => array(1301, 'complaint content is invalid'),
  'COMPLAINT_FAILED' => array(1302, 'complaint failed'),
  'COMPLAINT_ID_IS_INVALID' => array(1303, 'complaint id is invalid'),
  'COMPLAINT_IS_NOT_EXISTED' => array(1304, 'complaint is not existed'),
  'COMPLAINT_HANDLE_FAILED' => array(1305, 'complaint handle failed'),
  'COMPLAINT_CONTACT_IS_INVALID' => array(1306, 'complaint contact is invalid'),

  // Wechat
  'GET_JSAPI_TICKET_FAILED' => array(1401, 'get jsapi ticket failed'),
  'AUTHORIZE_CODE_IS_INVALID' => array(1402, 'authorize code is invalid'),
  'GET_OPEN_ID_FAILED' => array(1403, 'get open id failed'),
  'OPEN_ID_IS_INVALID' => array(1404, 'open id is invalid'),

  // Group
  'TITLE_IS_REQUIRE'                => array(1501, 'title is required'),
  'PRICE_IS_INVALID'                => array(1502, 'price is invalid'),
  'GROUP_ID_IS_INVAILD'             => array(1503, 'group id is invalid'),
  'GROUP_IS_NOT_EXISTED'            => array(1504, 'group is not existed'),
  'NAME_IS_REQUIRE'                 => array(1505, 'name is required'),
  'AMOUNT_IS_INVALID'               => array(1506, 'amount is invalid'),
  'ADD_ORDER_FAIL'                  => array(1507, 'add order fail'),
  'ALREADY_JOIN_THE_ACTIVITY'       => array(1508, 'already join the activity'),
  'ORDER_ID_IS_INVALID'             => array(1509, 'order id is invalid'),
  'PAY_TOKEN_IS_INVALID'            => array(1510, 'pay token is invalid'),
  'PAY_ORDER_FAIL'                  => array(1511, 'pay order fail'),
  'PAY_TOKEN_VERIFY_FAIL'           => array(1512, 'verify pay token fail'),
  'ORDER_NO_IS_REQUIRED'            => array(1513, 'order no is required'),
  'GET_GROUPS_FAIL'                 => array(1514, 'get groups fail'),
  'GET_ACTIVITY_IDS_FAIL'           => array(1515, 'get activity ids fail'),
  'ACCOUNT_IS_REQUIRED'             => array(1516, 'account is required'),
  'ADD_WITHDRAW_LOG_FAIL'           => array(1517, 'add withdraw log fail'),
  'MOBILE_IS_REQUIRE'               => array(1518, 'mobile is required'),
  'REMOVE_GROUP_USER_FAIL'          => array(1519, 'remove group user fail'),
  'REFUND_FAIL'                     => array(1520, 'refund fail'),
  'WXPAY_ADD_ORDER_FAIL'            => array(1521, 'wxpay add order fail'),
  'ACTIVITY_TYPE_WRONG'             => array(1522, 'activity type wrong'),
  'ACTIVITY_HAS_NOT_BEEN_COMPLETED' => array(1523, 'activity has not been completed'),
  'GET_GROUPS_TOTAL_PEOPLE_NUM_FAIL'=> array(1524, 'get groups total people num fail'),
  'GET_TOTAL_PAY_FAIL'              => array(1525, 'get total pay fail'),
  'WITHDRAW_AMOUNT_WRONG'           => array(1526, 'withdraw amount wrong'),
  'UPDATE_ORDER_FAIL'               => array(1527, 'update order fail'),
  'PAY_MESSAGE_IS_INVALID'          => array(1528, 'pay message is invalid'),
  'PAY_STATUS_IS_INVALID'           => array(1529, 'pay status is invalid'),
  'GROUP_HAD_BEEN_FULLED'           => array(1530, 'group had been fulled'),
  'GROUP_EXCEPTION_ORDER_ID_IS_INVALID' => array(1531, 'exception order id is invalid'),
  'GROUP_ORDER_IS_NOT_EXISTED'      => array(1532, 'group order is not existed'),
  'GROUP_ACTIVITY_NOT_BEGIN'        => array(1533, 'group activity has not yet begun'),
  'GROUP_ACTIVITY_IN_PROGRESS'      => array(1534, 'group activity in progress'),
  'GROUP_SETTLED_FAILED'            => array(1535, 'settle failed'),
  'GROUP_NO_BILLABLE_AMOUNT'        => array(1536, 'no billable amount'),

  // Statistics
  'STATISTIC_TYPE_IS_INVALID'           => array(1601, 'statistic type is invalid'),
  'STATISTIC_DATA_UPDATE_FAILED'        => array(1602, 'statistic data update failed'),

  // Withdrawals
  'WITHDRAWAL_ID_IS_INVALID'      => array(1701, 'withdrawal id is invalid'),
  'WITHDRAWAL_IS_NOT_EXISTED'     => array(1702, 'withdrawal is not existed'),
  'WITHDRAWAL_HANDLE_FAILED'      => array(1703, 'withdrawal handle failed'),

  // Backend
  'BACKEND_TABLE_ORDER_BY_IS_INVALID'           => array(1801, 'data list order by item is invalid'),
  'BACKEND_TABLE_ORDER_TYPE_IS_INVALID'         => array(1802, 'data list order type is invalid'),
  'BACKEND_SEARCH_STATISTIC_TYPE_IS_INVALID'    => array(1803, 'statistic search type is invalid'),
  'BACKEND_SEARCH_STATISTIC_KEYWORD_IS_INVALID' => array(1804, 'statistic search keyword is invalid'),
  'BACKEND_SEARCH_STATISTIC_STATUS_IS_INVALID'  => array(1805, 'statistic search status is invalid'),
  'BACKEND_SEARCH_STATISTIC_ID_IS_INVALID'      => array(1806, 'statistic search ID is invalid'),
  'BACKEND_SEARCH_COMPLAINT_TYPE_IS_INVALID'    => array(1807, 'complaint search type is invalid'),
  'BACKEND_SEARCH_COMPLAINT_KEYWORD_IS_INVALID' => array(1808, 'complaint search keyword is invalid'),
  'BACKEND_SEARCH_COMPLAINT_STATUS_IS_INVALID'  => array(1809, 'complaint search status is invalid'),
  'BACKEND_SEARCH_COMPLAINT_ID_IS_INVALID'      => array(1810, 'complaint search ID is invalid'),
  'BACKEND_SEARCH_CUSTOMER_ID_IS_INVALID'       => array(1811, 'customer search id is invalid'),
  'BACKEND_SEARCH_CUSTOMER_KEYWORD_IS_INVALID'  => array(1812, 'customer search keywords is invalid'),
  'BACKEND_SEARCH_CUSTOMER_AREA_IS_INVALID'     => array(1813, 'customer search area is invalid'),
  'BACKEND_SEARCH_CUSTOMER_INDUSTRY_IS_INVALID' => array(1814, 'customer search industry is invalid'),
  'BACKEND_SEARCH_CUSTOMER_STARTDATE_IS_INVALID'=> array(1815, 'customer search startdate is invalid'),
  'BACKEND_SEARCH_CUSTOMER_ENDDATE_IS_INVALID'  => array(1816, 'customer search enddate is invalid'),
  'BACKEND_SEARCH_CUSTOMER_STATUS_IS_INVALID'   => array(1817, 'customer search status is invalid'),

  'BACKEND_SEARCH_ACTIVITY_ID_IS_INVALID'       => array(1818, 'activity search id is invalid'),
  'BACKEND_SEARCH_ACTIVITY_USERID_IS_INVALID'   => array(1819, 'activity search userid is invalid'),
  'BACKEND_SEARCH_ACTIVITY_TYPE_IS_INVALID'     => array(1820, 'activity search type is invalid'),
  'BACKEND_SEARCH_ACTIVITY_KEYWORD_IS_INVALID'  => array(1821, 'activity search keywords is invalid'),
  'BACKEND_SEARCH_ACTIVITY_STATUS_IS_INVALID'   => array(1822, 'activity search status is invalid'),
  'BACKEND_SEARCH_ACTIVITY_TIME_STATUS_IS_INVALID'=> array(1823, 'activity search time status is invalid'),
  'BACKEND_SEARCH_ACTIVITY_STARTDATE_IS_INVALID'=> array(1824, 'activity search startdate is invalid'),
  'BACKEND_SEARCH_ACTIVITY_ENDDATE_IS_INVALID'  => array(1825, 'activity search enddate is invalid'),

  'BACKEND_USER_APPLICATION_ID_IS_INVALID'      => array(1826, 'user application ID is invalid'),
  'BACKEND_USER_APPLICATION_IS_NOT_EXIST'       => array(1827, 'user application is not exist'),
  'BACKEND_USER_APPLICATION_IGNORE_FAILED'      => array(1828, 'user application ignore failed'),
  'BACKEND_USER_APPLICATION_MODIFY_FAILED'      => array(1829, 'user application modify failed'),
  'BACKEND_USER_APPLICATION_HAS_BEEN_DONE'      => array(1830, 'user application has been done'),
  'BACKEND_USER_APPLICATION_PASS_FAILED'        => array(1831, 'user application pass failed'),
  
  'BACKEND_MESSAGE_SENDTO_IS_INVALID'           => array(1832, 'backend message send to is invalid'),
  'BACKEND_MESSAGE_TITLE_IS_INVALID'            => array(1833, 'backend message title is invalid'),
  'BACKEND_MESSAGE_CONTENT_IS_INVALID'          => array(1834, 'backend message content is invalid'),
  'BACKEND_MESSAGE_USER_ID_IS_NOT_EXIST'        => array(1835, 'backend message user id is not exist'),
  'BACKEND_MESSAGE_ID_IS_INVALID'               => array(1836, 'backend message id is invalid'),
  'BACKEND_SEARCH_MESSAGE_KEYWORDS_IS_INVALID'  => array(1837, 'backend search message keywords is invalid'),
  'BACKEND_MESSAGE_ADD_FAILED'                  => array(1838, 'backend message add failed'),
  'BACKEND_MESSAGE_IS_NOT_EXIST'                => array(1839, 'backend message is not exist'),
  'BACKEND_MESSAGE_DELETE_FAILED'               => array(1840, 'backend message delete failed'),
  'BACKEND_MESSAGE_REPLY_CONTENT_IS_INVALID'    => array(1841, 'backend message reply content is invalid'),
  'BACKEND_MESSAGE_POST_ID_IS_INVALID'          => array(1842, 'backend message post ID is invalid'),
  'BACKEND_MESSAGE_POST_RECORD_IS_NOT_EXIST'    => array(1843, 'backend message post record is not exist'),
  'BACKEND_MESSAGE_POST_REPLY_FAILED'           => array(1844, 'backend message post reply failed'),
  'BACKEND_MESSAGE_STATUS_IS_INVALID'           => array(1845, 'backend message status is invalid'),
  'BACKEND_MESSAGE_SET_TO_SENT_FAILD'           => array(1846, 'backend message set to sent failed'),
  'BACKEND_MESSAGE_HAS_EXISTED'                 => array(1847, 'backend message has existed'),
  'BACKEND_MESSAGE_MODIFY_FAILED'               => array(1848, 'backend message modify failed'),
  'BACKEND_MESSAGE_POST_REFER_INDEX_IS_INVALID' => array(1849, 'backend message post refer index is invalid'),
  'BACKEND_USER_EXPIRE_START_IS_INVALID'        => array(1850, 'backend user expirestart is invalid'),
  'BACKEND_USER_EXPIRE_END_IS_INVALID'          => array(1851, 'backend user expire end is invalid'),
  'BACKEND_ADMIN_ACTION_LOG_INSERT_FAILED'      => array(1852, 'backend admin action log insert failed'),
  'BACKEND_SEARCH_ACTION_LOGS_ACTION_TYPE_IS_INVALID' => array(1853, 'logs search action type is invalid'),
  'BACKEND_SEARCH_ACTION_LOGS_KEYWORD_IS_INVALID'     => array(1854, 'logs search keywords is invalid'),
  'BACKEND_SEARCH_ACTION_LOGS_STARTDATE_IS_INVALID'   => array(1855, 'logs search startdate is invalid'),
  'BACKEND_SEARCH_ACTION_LOGS_ENDDATE_IS_INVALID'     => array(1856, 'logs search enddate is invalid'),
  'BACKEND_USER_EXPIRE_NOTE_IS_INVALID'     => array(1857, 'backend user expire note is invalid'),
  'BACKEND_ACTION_LOG_ID_IS_INVALID'        => array(1858, 'backend action log id is invalid'),
  'BACKEND_ACTION_LOG_IS_NOT_EXIST'         => array(1859, 'backend action log is not exist'),
  'BACKEND_ACTION_LOG_MODIFY_FAILED'        => array(1860, 'backend action log modify failed'),
  'BACKEND_SEARCH_ORDER_TYPE_IS_INVALID'    => array(1861, 'backend search order type is invalid'),
  'BACKEND_SEARCH_ORDER_GROUP_ID_IS_INVALID'    => array(1862, 'backend search order group id is invalid'),
  'BACKEND_SEARCH_ORDER_KEYWORDS_IS_INVALID'    => array(1863, 'backend search order keywords is invalid'),
  'BACKEND_SEARCH_ORDER_STARTDATE_IS_INVALID'   => array(1864, 'orders search startdate is invalid'),
  'BACKEND_SEARCH_ORDER_ENDDATE_IS_INVALID'     => array(1865, 'orders search enddate is invalid'),
  'BACKEND_CUSTOMER_AMOUNT_IS_INVALID'   => array(1866, 'customer search customer amount is invalid'),
  'BACKEND_CUSTOMER_TOTAL_AMOUNT_IS_INVALID'  => array(1867, 'customer search customer total amount is invalid'),
  'BACKEND_CUSTOMER_REMARK_IS_INVALID'          => array(1868, 'customer remark is invalid'),
  'BACKEND_CUSTOMER_REMARK_FAILED'              => array(1869, 'customer remark failed'),
  'BACKEND_CUSTOMER_EXPIRE_UPDATE_TIME_IS_INVALID'  => array(1870, 'customer expire update time is invalid'),
  'BACKEND_CUSTOMER_EXPIRE_UPDATE_TIME_MODIFY_FAILIED' => array(1871, 'customer expire update time modify failed'),
  'BACKEND_CUSTOMER_AMOUNT_MODIFY_FAILIED'      => array(1872, 'customer amount modify failed'),
  'BACKEND_CUSTOMER_TOTAL_AMOUNT_MODIFY_FAILIED'=> array(1873, 'customer total amount modify failed'),
  'BACKEND_ACTIVITY_JOINER_ID_IS_INVALID'=> array(1874, 'joiner id is invalid'),
  'BACKEND_ACTIVITY_JOINER_NAME_IS_INVALID'=> array(1875, 'joiner name is invalid'),
  'BACKEND_ACTIVITY_JOINER_MOBILE_IS_INVALID'=> array(1876, 'joiner mobile is invalid'),
  'BACKEND_ACTIVITY_VOTER_IP_COUNT_IS_INVALID'=> array(1877, 'voter ip count is invalid'),
  'BACKEND_IP_ADDRESS_IS_INVALID'             => array(1878, 'IP is invalid'),
  'BACKEND_IP_ADDRESS_IS_PRIVATE_IP'          => array(1879, 'This is a interal network IP'),
  'BACKEND_IP_ADDRESS_HAS_BEEN_PULL_BLACK'    => array(1880, 'This ip has been pull black'),
  'BACKEND_IP_ADDRESS_PULL_BLACK_FAILED'      => array(1881, 'This ip pull black failed'),
  'BACKEND_IP_ADDRESS_REMOVE_BLACK_FAILED'    => array(1882, 'This ip remove black failed'),
  'BACKEND_FLYER_ID_IS_INVALID'               => array(1883, 'flyer id is invalid'),
  'BACKEND_FLYER_KEYWORD_IS_INVALID'          => array(1884, 'flyer keyword is invalid'),
  'BACKEND_FLYER_STARTDATE_IS_INVALID'        => array(1885, 'flyer search start date is invalid'),
  'BACKEND_FLYER_ENDDATE_IS_INVALID'          => array(1886, 'flyer search end date is invalid'),
  'BACKEND_FLYER_USER_ID_IS_INVALID'          => array(1887, 'flyer search userid is invalid'),
  'BACKEND_FLYER_CATEGORY_IS_INVALID'         => array(1888, 'flyer search category is invalid'),
  'BACKEND_INVITE_MOBILE_IS_INVALID'          => array(1889, 'invite search mobile is invalid'),
  'BACKEND_INVITE_SIGNUP_START_IS_INVALID'    => array(1890, 'invite search signup start is invalid'),
  'BACKEND_INVITE_SIGNUP_END_IS_INVALID'      => array(1891, 'invite search signup end is invalid'),
  'BACKEND_INVITE_RECHARGE_START_IS_INVALID'  => array(1892, 'invite search recharge start is invalid'),
  'BACKEND_INVITE_RECHARGE_END_IS_INVALID'    => array(1893, 'invite search recharge end is invalid'),
  'BACKEND_INVITE_INVITE_AMOUNT_MIN_IS_INVALID'     => array(1894, 'invite search invite amount min is invalid'),
  'BACKEND_INVITE_INVITE_AMOUNT_MAX_IS_INVALID'     => array(1895, 'invite search invite amount max is invalid'),
  'BACKEND_INVITE_RECHARGE_AMOUNT_MIN_IS_INVALID'   => array(1896, 'invite search recharge amount min is invalid'),
  'BACKEND_INVITE_RECHARG_AMOUNT_MAX_IS_INVALID'    => array(1897, 'invite search recharge amount max is invalid'),
  'BACKEND_INVITE_INVITER_ID_IS_INVALID'      => array(1898, 'invite search inviter id is invalid'),
  'BACKEND_USER_ID_IS_INVALID'                => array(1899, 'user id is invalid'),
  'BACKEND_ACCOUNT_FLOW_STATUS_IS_INVALID'    => array(1900, 'account flow status is invalid'),
  'BACKEND_ACCOUNT_FLOW_ACTION_IS_INVALID'    => array(1901, 'account flow action is invalid'),
  'BACKEND_RECHARGE_UNDO_FAILED'              => array(1902, 'recharge undo failed'),
  'BACKEND_RECHARGE_TIME_MODIFY_FAILED'       => array(1903, 'recharge time modify failed'),
  'BACKEND_RECHARGE_AMOUNT_MODIFY_FAILED'     => array(1904, 'recharge amount modify failed'),
  'BACKEND_RECHARGE_AMOUNT_IS_INVALID'        => array(1905, 'recharge amount is invalid'),
  'BACKEND_RECHARGE_TIME_IS_INVALID'          => array(1906, 'recharge time is invalid'),
  'BACKEND_WHITELIST_IP_ALREADY_EXISTS'           => array(1907, 'ip already exists'),

  // Message
  'MESSAGE_TYPE_IS_INVALID'                     => array(2001, 'message type is invalid'),
  'MESSAGE_IS_NOT_EXIST'                        => array(2002, 'message is not exist'),
  'MESSAGE_ID_IS_INVALID'                       => array(2003, 'message id is invalid'),
  'MESSAGE_POST_FAILED'                         => array(2004, 'message post failed'),
  'MESSAGE_POST_CONTENT_IS_INVALID'             => array(2005, 'message post content is invalid'),

  // Solitaire
  'SOLITAIRE_TITLE_IS_REQUIRE'                => array(2101, 'title is required'),
  'SOLITAIRE_PRICE_IS_INVALID'                => array(2102, 'price is invalid'),
  'SOLITAIRE_LIMIT_IS_INVALID'                => array(2103, 'limit is invalid'),
  'SOLITAIRE_ID_IS_INVAILD'                   => array(2104, 'solitaire id is invalid'),
  'SOLITAIRE_IS_NOT_EXISTED'                  => array(2105, 'solitaire is not existed'),
  'SOLITAIRE_NAME_IS_REQUIRE'                 => array(2106, 'name is required'),
  'SOLITAIRE_AMOUNT_IS_INVALID'               => array(2107, 'amount is invalid'),
  'SOLITAIRE_AVATOR_IS_REQUIRE'               => array(2108, 'avator is required'),
  'SOLITAIRE_ADD_ORDER_FAIL'                  => array(2109, 'add order fail'),
  'SOLITAIRE_ALREADY_JOIN_THE_ACTIVITY'       => array(2110, 'already join the activity'),
  'SOLITAIRE_ORDER_ID_IS_INVALID'             => array(2111, 'order id is invalid'),
  'SOLITAIRE_PAY_TOKEN_IS_INVALID'            => array(2112, 'pay token is invalid'),
  'SOLITAIRE_PAY_ORDER_FAIL'                  => array(2113, 'pay order fail'),
  'SOLITAIRE_PAY_TOKEN_VERIFY_FAIL'           => array(2114, 'verify pay token fail'),
  'SOLITAIRE_ORDER_NO_IS_REQUIRED'            => array(2115, 'order no is required'),
  'SOLITAIRE_GET_SOLITAIRES_FAIL'             => array(2116, 'get solitaires fail'),
  'SOLITAIRE_GET_ACTIVITY_IDS_FAIL'           => array(2117, 'get activity ids fail'),
  'SOLITAIRE_ACCOUNT_IS_REQUIRED'             => array(2118, 'account is required'),
  'SOLITAIRE_ADD_WITHDRAW_LOG_FAIL'           => array(2119, 'add withdraw log fail'),
  'SOLITAIRE_MOBILE_IS_REQUIRE'               => array(2120, 'mobile is required'),
  'SOLITAIRE_REMOVE_GROUP_USER_FAIL'          => array(2121, 'remove group user fail'),
  'SOLITAIRE_REFUND_FAIL'                     => array(2122, 'refund fail'),
  'SOLITAIRE_WXPAY_ADD_ORDER_FAIL'            => array(2123, 'wxpay add order fail'),
  'SOLITAIRE_ACTIVITY_TYPE_WRONG'             => array(2124, 'activity type wrong'),
  'SOLITAIRE_ACTIVITY_HAS_NOT_BEEN_COMPLETED' => array(2125, 'activity has not been completed'),
  'SOLITAIRE_GET_GROUPS_TOTAL_PEOPLE_NUM_FAIL'=> array(2126, 'get groups total people num fail'),
  'SOLITAIRE_GET_TOTAL_PAY_FAIL'              => array(2127, 'get total pay fail'),
  'SOLITAIRE_WITHDRAW_AMOUNT_WRONG'           => array(2128, 'withdraw amount wrong'),
  'SOLITAIRE_UPDATE_ORDER_FAIL'               => array(2129, 'update order fail'),
  'SOLITAIRE_PAY_MESSAGE_IS_INVALID'          => array(2130, 'pay message is invalid'),
  'SOLITAIRE_PAY_STATUS_IS_INVALID'           => array(2131, 'pay status is invalid'),
  'SOLITAIRE_HAD_BEEN_FULLED'                 => array(2132, 'group had been fulled'),
  'SOLITAIRE_EXCEPTION_ORDER_ID_IS_INVALID'   => array(2133, 'exception order id is invalid'),
  'SOLITAIRE_ORDER_IS_NOT_EXISTED'            => array(2134, 'group order is not existed'),
  'SOLITAIRE_ACTIVITY_NOT_BEGIN'              => array(2135, 'group activity has not yet begun'),
  'SOLITAIRE_ACTIVITY_IN_PROGRESS'            => array(2136, 'group activity in progress'),
  'SOLITAIRE_JOINER_ID_IS_INVALID'            => array(2137, 'joiner id is invalid'),
  'SOLITAIRE_JOINER_FIELD_IS_INVALID'         => array(2138, 'joiner customize field is invalid'),
  'SOLITAIRE_JOINER_FIELD_VALUE_IS_INVALID'       => array(2139, 'joiner customize field value is invalid'),
  'SOLITAIRE_JOINER_CUSTOMIZE_INFO_MODIFY_FAILED' => array(2140, 'joiner customize info modify failed'),
  'SOLITAIRE_PRIZES_IS_INVALID'                => array(2141, 'prizes is invalid'),
  'SOLITAIRE_SETTLED_FAILED'            => array(2142, 'settle failed'),
  'SOLITAIRE_NO_BILLABLE_AMOUNT'        => array(2143, 'no billable amount'),
  'SOLITAIRE_NOT_BEEN_GROUPED'          => array(2144, 'solitaire is not been grouped'),

  // Flyer
  'FLYER_CONTENT_IS_INVAILD'  => array(2201, 'content is invalid'),
  'FLYER_ID_IS_INVALID'       => array(2202, 'id is invalid'),
  'FLYER_IS_NOT_EXISTED'      => array(2203, 'flyer is not existed'),
  'FLYER_SAVE_FAILED'         => array(2204, 'flyer save failed'),
  'FLYER_DELETE_FAILED'       => array(2205, 'flyer delete failed'),
  'FLYER_NAME_SAVE_FAILED'    => array(2206, 'flyer name save failed'),
  'FLYER_DOWNLOAD_FAILED'     => array(2207, 'flyer download failed'),
  'FLYER_NAME_IS_REQUIRED'    => array(2208, 'name is required'),
  'FLYER_DOWNLOAD_PARAMS_IS_REQUIRED' => array(2209, 'download params is required'),
  'FLYER_TEMPLATE_KEY_IS_INVALID' => array(2210, 'template key is invalid'),
  'FLYER_TEMPLATE_GET_FAILED' => array(2211, 'template data get failed'),
  'FLYER_NAME_IS_INVAILD' => array(2212, 'flyer name is invalid'),
  'FLYER_CATEGORY_IS_INVAILD' => array(2213, 'flyer category is invalid'),


  // Lottery
  'HAS_REACH_THE_MAX_LOTTERY_NUM' => array(2301, 'has reach the max lottery num'),
  'LOTTERY_CURRENTLY_UNABLE_TO_LOTTERY'   => array(2302, 'currently unable to lottery'),
  'NO_PRIZES_TO_LOTTERY'  => array(2303, 'no prizes to lottery'),
  'LOTTERY_FAILED'  => array(2304, 'lottery failed'),
  'LOTTERY_EXCHANGE_PASSWORD_IS_INVALID'  => array(2305, 'lottery exchange password is invalid'),
  'HAS_REACH_THE_MAX_WINNING_NUM'  => array(2306, 'has reach the max winning num'),

  // Texter
  'TEXTER_CONTENT_IS_REQUIRE' => array(2401, 'content is require'),
  'TEXTER_CONFIG_IS_REQUIRE' => array(2402, 'config is require'),
  'TEXTER_IS_NOT_EXISTED' => array(2403, 'texter is not existed'),
  'TEXTER_SAVE_FAILED' => array(2404, 'texter save failed'),
  'TEXTER_ID_IS_INVALID' => array(2405, 'texter id is invalid'),
  'TEXTER_POST_NICKNAME_IS_INVALID' => array(2406, 'nickname is invalid'),
  'TEXTER_POST_CONTENT_IS_REQUIRE' => array(2407, 'content is require'),
  'TEXTER_POST_ID_IS_INVALID' => array(2408, 'post id is invalid'),
  'TEXTER_POST_IS_NOT_EXISTED' => array(2409, 'post is not existed'),
  'TEXTER_POST_IMG_IS_REQUEIRE' => array(2410, 'texter img is require'),
  'TEXTER_POST_SAVE_FAILED' => array(2411, 'texter post save failed'),
  'TEXTER_DELETE_FAILED' => array(2412, 'texter delete failed'),
  'TEXTER_POST_DELETE_FAILED' => array(2413, 'post delete failed'),
  'TEXTER_POST_GOOD_FAILED' => array(2414, 'post good failed'),
  'TEXTER_POST_REPLY_FAILED' => array(2415, 'post reply failed'),
  'TEXTER_POST_REPLY_DELETE_FAILED' => array(2416, 'post reply delete failed'),
  'TEXTER_POST_REPLY_TOP_DELETE_FAILED' => array(2417, 'post reply delete top failed'),
  'TEXTER_POST_REPLY_TOTOP_FAILED' => array(2418, 'post reply top failed'),
  'TEXTER_POST_TOP_DELETE_FAILED' => array(2419, 'post top delete failed'),
  

  // multi goods activity
  'GOODS_INFO_FORMAT_IS_INVALID' => array(2501, 'goods info is invalid'),
  'BARGAIN_RULES_FORMAT_IS_INVALID' => array(2502, 'bargain rules info is invalid'),
  'BARGAIN_PRICE_CHANGE_IS_INVALID' => array(2503, 'Has a user registration, the low price of goods, the original price can not be modified'),
  'GOODS_COUNT_CHANGE_IS_INVALID' => array(2504, 'Has a user registration, the goods count can not be lower'),
  'GOODS_BARGAIN_TO_REACH_MAXIMUM' => array(2505, 'bargain goods to reach maximum, can not join again'),
  'GOODS_PRICE_IS_FLOOR_PRICE' => array(2506, 'Has reached the lowest price of goods'),
  'BARGAIN_GOODS_DELETE_FAILED_USER' => array(2507, 'goods delete failed, user is join'),
  'BARGAIN_GOODS_DELETE_FAILED' => array(2508, 'bargain goods activity delete failed'),
  'BARGAIN_ACTIVITY_DELETE_FAILED_USER' => array(2509, 'bargain activity delete failed, user is join'),
  'BARGAIN_GOODS_ACTIVITY_NOT_END' => array(2510, 'bargain goods activity is not end,cant\'t withdraw'),
  'BARGAIN_GOODS_ORDER_IS_WRONG' => array(2511, 'bargain goods order fail, goods stock is null'),
  'ALREADY_PAID' => array(2512, 'Payment has been completed'),
  'ACTIVITY_IS_SETTLED' => array(2513, 'activity is settled'),
  'YOU_HAVE_ALREADY_BARGAIN' => array(2514, 'you have already bargain'),
  'JOIN_ACTIVITY_FAILED_FIELD' => array(2515, 'join activity failed, field not enough'),
  'BARGAIN_TARGET_HAS_BEEN_COMPLETED' => array(2516, 'bargain target has been completed'),
  'GOODS_STOCK_NOT_ENOUGH' => array(2517, 'goods stock not enough'),
  'BARGAIN_PRICE_HAS_BEEN_COMPLETED' => array(2518, 'bargain price has been completed'),
  'JOINER_INFO_NOT_FOUND' => array(2519, 'joiner info not found'),
  'ACTIVITY_COPY_FAIL' => array(2520, 'activity copy fail'),
  'GOODS_COPY_FAIL' => array(2521, 'goods copy fail'),
  'GOODS_IS_NOT_EXIST' => array(2522, 'goods is not exist'),
  'ORDER_EXCEPTION' => array(2523, 'order exception'),

  // Gift vote
  'GIFTVOTE_PACKAGE_ID_IS_INVALID'  => array(2601, 'package id is invalid'),
  'GIFTVOTE_PACKAGE_IS_NOT_EXISTED' => array(2602, 'package is not existed'),
  'GIFTVOTE_ADD_ORDER_FAIL'         => array(2603, 'add order fail'),
  'GIFTVOTE_WXPAY_ADD_ORDER_FAIL'   => array(2604, 'wxpay add order fail'),
  'GIFTVOTE_UPDATE_ORDER_FAIL'      => array(2605, 'update order fail'),

  //photovote extents activity
  'AREA_IS_NOT_ALLOW_VOTE'  => array(4001, 'area is not allow vote'),
  'IP_IS_NOT_RIGHT'  => array(4002, 'ip address is not righit'),
  'HAS_ALREADY_REACH_HOUR_VOTE_LIMIT'  => array(4003, 'already reach hour vote limit'),
  'ACTIVITY_MEMBER_IS_NOT_EXIST'  => array(4004, 'activity member is not exist'),
  'JOINER_MEMBER_IS_NOT_VERIFY'  => array(4005, 'joiner member is not verify '),

);



